// AUTO-GENERATED by scripts/svg-forge.ts --compile — DO NOT EDIT BY HAND.
// Re-run: npx tsx scripts/svg-forge.ts --compile

import React from "react";

export interface SvgLibraryChildProps {
  strokeWidth?: number;
}

export const SVG_LIBRARY: Record<string, React.FC<SvgLibraryChildProps>> = {
  "notebook-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<rect x="18" y="10" width="84" height="100" rx="3" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="33" y1="10" x2="33" y2="110" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="44" y1="36" x2="94" y2="36" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="44" y1="52" x2="94" y2="52" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="44" y1="68" x2="94" y2="68" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="44" y1="84" x2="94" y2="84" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <polyline points="54,10 54,2 63,7 72,2 72,10" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "monitor-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<rect x="8" y="12" width="104" height="76" rx="6" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <rect x="16" y="20" width="88" height="60" rx="2" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="88" x2="60" y2="106" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="38" y1="106" x2="82" y2="106" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "laptop-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<rect x="18" y="10" width="84" height="58" rx="4" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <rect x="24" y="17" width="72" height="44" rx="2" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="60" cy="14" r="2" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="15" y1="70" x2="105" y2="70" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <rect x="12" y="74" width="96" height="22" rx="4" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <rect x="45" y="80" width="30" height="12" rx="3" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "lock-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<rect x="22" y="58" width="76" height="50" rx="7" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M 37 58 L 37 38 A 23 23 0 0 1 83 38 L 83 58" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="60" cy="78" r="7" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="85" x2="60" y2="96" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "globe-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<circle cx="60" cy="60" r="45" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <ellipse cx="60" cy="60" rx="45" ry="13" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <ellipse cx="60" cy="60" rx="13" ry="45" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M 21 38 Q 60 46 99 38" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M 21 82 Q 60 74 99 82" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "cloud-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<path d="M22,72 Q8,72 8,58 Q8,42 24,42 Q24,24 46,28 Q50,14 68,16 Q88,14 90,32 Q108,34 108,52 Q112,68 98,72 Z" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="72" x2="60" y2="84" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <rect x="36" y="84" width="48" height="14" rx="3" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="44" y1="91" x2="60" y2="91" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="73" cy="91" r="3" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "key-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<circle cx="34" cy="58" r="22" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="34" cy="58" r="10" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="56" y1="58" x2="98" y2="58" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="76" y1="58" x2="76" y2="73" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="89" y1="58" x2="89" y2="68" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "server-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<rect x="20" y="15" width="80" height="90" rx="3" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="20" y1="45" x2="100" y2="45" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="20" y1="75" x2="100" y2="75" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="35" cy="30" r="4" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="35" cy="60" r="4" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="35" cy="90" r="4" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="50" y1="30" x2="90" y2="30" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="50" y1="60" x2="90" y2="60" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "database-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<ellipse cx="60" cy="28" rx="34" ry="10" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="26" y1="28" x2="26" y2="92" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="94" y1="28" x2="94" y2="92" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <ellipse cx="60" cy="92" rx="34" ry="10" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M 26,51 A 34,10 0 0 1 94,51" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M 26,70 A 34,10 0 0 1 94,70" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "folder-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<path d="M17 42 L17 30 Q17 27 20 27 L49 27 Q52 27 54 30 L58 42 L103 42 Q106 42 106 45 L106 91 Q106 94 103 94 L17 94 Q14 94 14 91 L14 45 Q14 42 17 42 Z" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "terminal-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<rect x="8" y="12" width="104" height="96" rx="5" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="8" y1="28" x2="112" y2="28" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <polyline points="22,46 33,55 22,64" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="38" y1="55" x2="62" y2="55" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="22" y1="72" x2="82" y2="72" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="22" y1="84" x2="66" y2="84" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "document-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<path d="M22,12 L78,12 L98,32 L98,108 L22,108 Z" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M78,12 L78,32 L98,32" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="36" y1="52" x2="84" y2="52" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="36" y1="67" x2="84" y2="67" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="36" y1="82" x2="64" y2="82" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "bar-chart-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<line x1="18" y1="15" x2="18" y2="97" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="18" y1="97" x2="107" y2="97" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <rect x="26" y="72" width="14" height="25" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <rect x="45" y="37" width="14" height="60" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <rect x="64" y="52" width="14" height="45" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <rect x="83" y="62" width="14" height="35" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "chart-up-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<line x1="20" y1="100" x2="20" y2="14" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="20" y1="100" x2="108" y2="100" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <polyline points="26,88 45,72 62,54 80,36 100,18" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="100" y1="18" x2="90" y2="24" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="100" y1="18" x2="94" y2="28" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="45" cy="72" r="4" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="62" cy="54" r="4" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="80" cy="36" r="4" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "chart-down-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<line x1="22" y1="12" x2="22" y2="95" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="22" y1="95" x2="108" y2="95" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <polyline points="28,24 48,38 65,52 82,66 98,82" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="98" y1="82" x2="85" y2="80" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="98" y1="82" x2="96" y2="69" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "gear-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<path d="M48.5 30.1 L55 28.4 L53.1 16.5 L66.9 16.5 L65 28.4 L71.5 30.1 L80.1 35.1 L84.9 39.9 L94.2 32.3 L101.1 44.2 L89.9 48.5 L91.6 55 L91.6 65 L89.9 71.5 L101.1 75.8 L94.2 87.7 L84.9 80.1 L80.1 84.9 L71.5 89.9 L65 91.6 L66.9 103.5 L53.1 103.5 L55 91.6 L48.5 89.9 L39.9 84.9 L35.1 80.1 L25.8 87.7 L18.9 75.8 L30.1 71.5 L28.4 65 L28.4 55 L30.1 48.5 L18.9 44.2 L25.8 32.3 L35.1 39.9 L39.9 35.1 Z" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="60" cy="60" r="13" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "clock-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<circle cx="60" cy="60" r="48" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="14" x2="60" y2="23" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="106" y1="60" x2="97" y2="60" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="106" x2="60" y2="97" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="14" y1="60" x2="23" y2="60" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="60" x2="37" y2="44" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="60" x2="95" y2="40" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="60" cy="60" r="4" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "calendar-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<rect x="14" y="26" width="92" height="80" rx="7" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="14" y1="48" x2="106" y2="48" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="37" y1="14" x2="37" y2="37" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="83" y1="14" x2="83" y2="37" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="24" y1="64" x2="96" y2="64" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="24" y1="80" x2="96" y2="80" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="60" cy="93" r="7" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "ring-chart-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<circle cx="60" cy="60" r="44" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="60" cy="60" r="24" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="36" x2="60" y2="16" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="84" y1="60" x2="104" y2="60" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="39" y1="48" x2="22" y2="38" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "pie-chart-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<circle cx="60" cy="60" r="40" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="60" x2="60" y2="20" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="60" x2="95" y2="80" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="60" x2="22" y2="74" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "coin-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<ellipse cx="60" cy="35" rx="44" ry="12" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="16" y1="35" x2="16" y2="85" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="104" y1="35" x2="104" y2="85" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M16,85 A44,12 0 0 1 104,85" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <ellipse cx="60" cy="35" rx="30" ry="8" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="60" cy="35" r="6" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "briefcase-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<rect x="12" y="46" width="96" height="60" rx="6" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M 38,46 L 38,30 Q 60,17 82,30 L 82,46" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <rect x="51" y="39" width="18" height="13" rx="3" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="12" y1="69" x2="108" y2="69" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "shield-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<path d="M 18,18 L 102,18 L 102,68 Q 102,100 60,112 Q 18,100 18,68 Z" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <polyline points="38,63 52,77 82,47" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "hourglass-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<polygon points="18,12 102,12 66,60 102,108 18,108 54,60" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="54" y1="60" x2="66" y2="60" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="39" y1="40" x2="81" y2="40" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="62" x2="60" y2="78" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <ellipse cx="60" cy="100" rx="22" ry="5" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "rocket-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<path d="M 60 14 C 47 30 46 55 47 82 L 73 82 C 74 55 73 30 60 14 Z" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M 47 65 L 30 88 L 47 82 Z" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M 73 65 L 90 88 L 73 82 Z" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="60" cy="46" r="8" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="50" y1="75" x2="70" y2="75" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M 52 82 C 48 94 54 108 60 104 C 66 108 72 94 68 82" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "brain-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<path d="M60,26 C51,20 33,22 24,37 C16,52 20,73 33,83 C44,91 56,89 60,84" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M60,26 C69,20 87,22 96,37 C104,52 100,73 87,83 C76,91 64,89 60,84" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="26" x2="60" y2="84" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M37,40 C40,35 47,36 49,41" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M30,59 C34,53 42,54 44,60" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M83,40 C80,35 73,36 71,41" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M90,59 C86,53 78,54 76,60" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M51,85 C51,94 55,97 60,97 C65,97 69,94 69,85" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "eye-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<path d="M15,60 C30,34 90,34 105,60 C90,86 30,86 15,60Z" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="60" cy="60" r="16" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="60" cy="60" r="4" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "arrow-right-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<line x1="15" y1="60" x2="84" y2="60" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <polyline points="65,36 97,60 65,84" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "lightbulb-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<path d="M 42,74 C 28,64 28,20 60,20 C 92,20 92,64 78,74" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="42" y1="74" x2="78" y2="74" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="44" y1="82" x2="76" y2="82" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="46" y1="90" x2="74" y2="90" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <polyline points="50,65 55,48 60,58 65,48 70,65" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "tool-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<polygon points="22,12 62,32 44,70 4,50" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <polygon points="52,44 104,96 96,104 44,52" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "target-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<circle cx="60" cy="60" r="52" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="60" cy="60" r="35" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="60" cy="60" r="18" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="60" cy="60" r="5" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="98" y1="14" x2="60" y2="60" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <polyline points="70,55 60,60 62,49" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "arrow-curve-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<path d="M 20 100 C 20 20 20 20 100 20" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <polyline points="87,10 100,20 87,30" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "branching-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<line x1="60" y1="108" x2="60" y2="64" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="64" x2="28" y2="38" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="64" x2="92" y2="38" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="28" y1="38" x2="13" y2="14" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="28" y1="38" x2="43" y2="14" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="92" y1="38" x2="77" y2="14" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="92" y1="38" x2="107" y2="14" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "merge-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<circle cx="28" cy="22" r="5" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="92" cy="22" r="5" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="60" cy="98" r="5" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M28 27 C28 60 60 58 60 68" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M92 27 C92 60 60 58 60 68" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="68" x2="60" y2="93" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "layers-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<polygon points="60,18 100,33 60,48 20,33" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <polygon points="60,42 100,57 60,72 20,57" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <polygon points="60,66 100,81 60,96 20,81" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "pulse-wave-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<polyline points="5,72 30,72 38,60 50,18 62,98 70,72 115,72" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="50" cy="18" r="5" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="50" cy="18" r="11" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="50" cy="18" r="19" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "spark-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<circle cx="60" cy="60" r="5" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="60" x2="60" y2="15" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="60" x2="98" y2="36" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="60" x2="105" y2="64" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="60" x2="90" y2="95" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="60" x2="44" y2="106" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="60" x2="16" y2="84" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="60" x2="14" y2="40" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "hand-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<path d="M 34 108 L 34 72 L 34 52 Q 34 44 39 44 Q 44 44 44 52 L 44 72 L 47 72 L 47 38 Q 47 30 52 30 Q 57 30 57 38 L 57 72 L 60 72 L 60 24 Q 60 16 65 16 Q 70 16 70 24 L 70 72 L 73 72 L 73 38 Q 73 30 78 30 Q 83 30 83 38 L 83 68 C 86 66 90 62 90 57 Q 90 51 86 51 Q 82 51 81 57 L 81 68 C 82 74 83 82 84 108 Z" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "network-nodes-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<circle cx="60" cy="58" r="9" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="20" cy="20" r="5" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="95" cy="25" r="5" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="88" cy="95" r="5" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="58" x2="20" y2="20" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="58" x2="95" y2="25" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="58" x2="88" y2="95" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="20" y1="20" x2="95" y2="25" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "refresh-loop-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<path d="M 28,60 A 32,32 0 0,1 92,60" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <polyline points="98,52 92,60 86,52" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M 92,60 A 32,32 0 0,1 28,60" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <polyline points="34,68 28,60 22,68" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "plus-grid-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<path d="M11,22 L33,22 M49,22 L71,22 M87,22 L109,22 M11,60 L33,60 M49,60 L71,60 M87,60 L109,60 M11,98 L33,98 M49,98 L71,98 M87,98 L109,98" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M22,11 L22,33 M22,49 L22,71 M22,87 L22,109 M60,11 L60,33 M60,49 L60,71 M60,87 L60,109 M98,11 L98,33 M98,49 L98,71 M98,87 L98,109" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "connection-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<circle cx="60" cy="57" r="11" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="20" cy="24" r="8" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="100" cy="24" r="8" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="72" cy="101" r="8" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="27" y1="30" x2="50" y2="48" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="93" y1="30" x2="70" y2="48" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="66" y1="68" x2="72" y2="93" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "weight-scale-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<line x1="45" y1="108" x2="75" y2="108" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="108" x2="60" y2="40" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="60" cy="40" r="4" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="15" y1="47" x2="105" y2="33" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="15" y1="47" x2="15" y2="76" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="105" y1="33" x2="105" y2="62" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M 5,76 Q 15,83 25,76" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M 95,62 Q 105,69 115,62" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "ladder-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<line x1="33" y1="8" x2="33" y2="112" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="87" y1="8" x2="87" y2="112" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="33" y1="28" x2="87" y2="28" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="33" y1="46" x2="87" y2="46" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="33" y1="64" x2="87" y2="64" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="33" y1="82" x2="87" y2="82" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="33" y1="100" x2="87" y2="100" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "zigzag-path-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<polyline points="15,98 42,22 70,80 97,18" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="15" cy="98" r="5" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="42" cy="22" r="4" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="70" cy="80" r="4" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="97" y1="18" x2="84" y2="24" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="97" y1="18" x2="92" y2="31" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "puzzle-piece-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<path d="M 25,35 L 48,35 C 48,25 52,12 60,12 C 68,12 72,25 72,35 L 95,35 L 95,48 C 105,48 112,55 112,60 C 112,65 105,72 95,72 L 95,95 L 72,95 C 72,105 68,110 60,110 C 52,110 48,105 48,95 L 25,95 L 25,72 C 15,72 8,65 8,60 C 8,55 15,48 25,48 Z" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "bridge-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<line x1="8" y1="72" x2="112" y2="72" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="38" y1="42" x2="38" y2="88" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="82" y1="42" x2="82" y2="88" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M12,60 L38,42 Q60,64 82,42 L108,60" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="53" x2="60" y2="72" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="49" y1="50" x2="49" y2="72" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="71" y1="50" x2="71" y2="72" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "flag-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<line x1="38" y1="18" x2="38" y2="102" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M38,22 L86,36 L38,54" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="20" y1="102" x2="56" y2="102" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "door-open-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<path d="M 25,100 L 25,15 L 75,15 L 75,100" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="13" y1="100" x2="103" y2="100" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <path d="M 25,15 L 52,21 L 52,93 L 25,100" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="49" cy="63" r="4" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="76" y1="27" x2="100" y2="16" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="76" y1="50" x2="104" y2="48" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="76" y1="73" x2="100" y2="82" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
  "compass-line": ({ strokeWidth }) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 120 120" fill="none" width="100%" height="100%" aria-hidden="true">
<circle cx="60" cy="60" r="50" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <polygon points="60,20 68,64 52,64" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <polygon points="60,100 52,58 68,58" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <circle cx="60" cy="60" r="4" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="10" x2="60" y2="18" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="110" y1="60" x2="102" y2="60" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="10" y1="60" x2="18" y2="60" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
  <line x1="60" y1="110" x2="60" y2="102" fill="none" stroke="currentColor" strokeWidth={strokeWidth ?? 3.5} strokeLinecap="round" strokeLinejoin="round" />
    </svg>
  ),
};
