// @TASK P1.5-SK4-T1 - Remotion Builder 서비스
// @SPEC Scene DSL -> Remotion TSX 자동 생성
// @TEST tests/services/remotion-builder.test.ts

import fs from "fs/promises";
import path from "path";
import type { Scene } from "@/types/index";

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface RemotionBuildResult {
  outputDir: string;
  compositionFile: string;
  totalFrames: number;
  fps: number;
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

const DEFAULT_FPS = 30;

// ---------------------------------------------------------------------------
// generateCompositionTSX
// ---------------------------------------------------------------------------

/**
 * Scene DSL 배열을 받아 Remotion TSX 코드 문자열을 생성합니다.
 * 생성된 TSX는 AbsoluteFill + Series 패턴으로 각 Scene을 순차 렌더링합니다.
 */
export function generateCompositionTSX(scenes: Scene[]): string {
  const totalFrames = scenes.reduce(
    (sum, scene) => sum + scene.duration_frames,
    0
  );

  const scenesJson = JSON.stringify(scenes, null, 2);

  return `// Auto-generated by /vg-render
// Total frames: ${totalFrames}, FPS: ${DEFAULT_FPS}
import { AbsoluteFill, Series } from "remotion";
import { SceneRenderer } from "../remotion/common/SceneRenderer";

const scenes = ${scenesJson};

export const GeneratedComposition = () => (
  <AbsoluteFill>
    <Series>
      {scenes.map((scene) => (
        <Series.Sequence key={scene.id} durationInFrames={scene.duration_frames}>
          <SceneRenderer scene={scene} frame={0} />
        </Series.Sequence>
      ))}
    </Series>
  </AbsoluteFill>
);
`;
}

// ---------------------------------------------------------------------------
// writeGeneratedComposition
// ---------------------------------------------------------------------------

/**
 * Scene DSL -> TSX 코드를 생성하고 파일로 씁니다.
 * outputDir에 Composition.tsx 파일을 생성합니다.
 */
export async function writeGeneratedComposition(
  scenes: Scene[],
  outputDir: string
): Promise<RemotionBuildResult> {
  const totalFrames = scenes.reduce(
    (sum, scene) => sum + scene.duration_frames,
    0
  );

  // 출력 디렉토리 생성
  await fs.mkdir(outputDir, { recursive: true });

  // TSX 생성
  const tsxContent = generateCompositionTSX(scenes);
  const compositionFile = path.join(outputDir, "Composition.tsx");

  // 파일 쓰기
  await fs.writeFile(compositionFile, tsxContent, "utf-8");

  return {
    outputDir,
    compositionFile,
    totalFrames,
    fps: DEFAULT_FPS,
  };
}
